CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Games" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StartTime" timestamp with time zone NOT NULL,
    "HomeTeam" text NOT NULL,
    "AwayTeam" text NOT NULL,
    "HomeScore" integer,
    "AwayScore" integer,
    "IsFinal" boolean NOT NULL,
    "OddsClosed" boolean NOT NULL,
    "HomeOdds" numeric NOT NULL,
    "AwayOdds" numeric NOT NULL,
    "DrawOdds" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Leagues" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OwnerId" bigint NOT NULL,
    "Name" text NOT NULL,
    "IsPublic" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Sport" integer NOT NULL,
    CONSTRAINT "PK_Leagues" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Leagues_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "LeagueUser" (
    "MemberLeaguesId" bigint NOT NULL,
    "MembersId" bigint NOT NULL,
    CONSTRAINT "PK_LeagueUser" PRIMARY KEY ("MemberLeaguesId", "MembersId"),
    CONSTRAINT "FK_LeagueUser_Leagues_MemberLeaguesId" FOREIGN KEY ("MemberLeaguesId") REFERENCES "Leagues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeagueUser_Users_MembersId" FOREIGN KEY ("MembersId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Schedules" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "GameId" bigint NOT NULL,
    "LeagueId" bigint NOT NULL,
    "PicksClosed" boolean NOT NULL,
    CONSTRAINT "PK_Schedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Schedules_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Schedules_Leagues_LeagueId" FOREIGN KEY ("LeagueId") REFERENCES "Leagues" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Picks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "GameLeagueId" bigint NOT NULL,
    "Wager" numeric NOT NULL,
    "TeamType" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Picks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Picks_Schedules_GameLeagueId" FOREIGN KEY ("GameLeagueId") REFERENCES "Schedules" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Picks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Leagues_OwnerId" ON "Leagues" ("OwnerId");

CREATE INDEX "IX_LeagueUser_MembersId" ON "LeagueUser" ("MembersId");

CREATE INDEX "IX_Picks_GameLeagueId" ON "Picks" ("GameLeagueId");

CREATE INDEX "IX_Picks_UserId" ON "Picks" ("UserId");

CREATE INDEX "IX_Schedules_GameId" ON "Schedules" ("GameId");

CREATE INDEX "IX_Schedules_LeagueId" ON "Schedules" ("LeagueId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250411204428_InitialMigration', '9.0.4');

COMMIT;

