START TRANSACTION;
ALTER TABLE "Picks" DROP CONSTRAINT "FK_Picks_Schedules_GameLeagueId";

DROP INDEX "IX_Picks_GameLeagueId";

ALTER TABLE "Leagues" DROP COLUMN "Sport";

ALTER TABLE "Games" DROP COLUMN "Season";

ALTER TABLE "Games" DROP COLUMN "Sport";

ALTER TABLE "Picks" ADD "GameId" bigint NOT NULL DEFAULT 0;

ALTER TABLE "Leagues" ADD "SportId" bigint NOT NULL DEFAULT 0;

ALTER TABLE "Games" ADD "SportId" bigint NOT NULL DEFAULT 0;

CREATE TABLE "Sports" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Season" text NOT NULL,
    "Week" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Sports" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Picks_GameId" ON "Picks" ("GameId");

CREATE INDEX "IX_Leagues_SportId" ON "Leagues" ("SportId");

CREATE INDEX "IX_Games_SportId" ON "Games" ("SportId");

ALTER TABLE "Games" ADD CONSTRAINT "FK_Games_Sports_SportId" FOREIGN KEY ("SportId") REFERENCES "Sports" ("Id") ON DELETE CASCADE;

ALTER TABLE "Leagues" ADD CONSTRAINT "FK_Leagues_Sports_SportId" FOREIGN KEY ("SportId") REFERENCES "Sports" ("Id") ON DELETE CASCADE;

ALTER TABLE "Picks" ADD CONSTRAINT "FK_Picks_Schedules_GameId" FOREIGN KEY ("GameId") REFERENCES "Schedules" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250507171242_AddSport', '9.0.4');

COMMIT;

